apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-i2fb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-i2fb
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-i2fb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-i2fb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-i2fb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rimo-tenant/status-quarkus-io/statusquarkusio-i2fb@sha256:6ea66516988ced412d9d06d7593231b4bd60c78c2c98e049bd420aaef2c5b187
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
